

export const mockProducts = [
  {
    id: 'p1',
    title: 'Premium Wireless Headphones',
    description: 'Immerse yourself in high-quality sound with these premium wireless headphones. Featuring noise cancellation, 30-hour battery life, and comfortable over-ear design.',
    price: 199.99,
    originalPrice: 249.99,
    categoryId: 'electronics',
    rating: 4.7,
    reviewCount: 254,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/3394651/pexels-photo-3394651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    tags: ['headphones', 'audio', 'wireless', 'noise-cancellation'],
    stock: 45,
    featured: true,
    isSale: true,
    specifications: {
      'Bluetooth Version': '5.0',
      'Battery Life': '30 hours',
      'Charging Time': '2 hours',
      'Noise Cancellation': 'Active',
      'Weight': '250g',
    },
    createdAt: '2023-11-15T10:30:00Z',
  },
  {
    id: 'p2',
    title: 'Ultra HD Smart TV - 55"',
    description: 'Experience stunning 4K resolution with this Ultra HD Smart TV. Featuring built-in streaming apps, voice control, and a sleek design to enhance your home entertainment.',
    price: 699.99,
    originalPrice: 849.99,
    categoryId: 'electronics',
    rating: 4.5,
    reviewCount: 189,
    image: 'https://images.pexels.com/photos/333984/pexels-photo-333984.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/333984/pexels-photo-333984.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/333985/pexels-photo-333985.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/333986/pexels-photo-333986.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    tags: ['tv', 'smart tv', '4k', 'ultra hd', 'home theater'],
    stock: 32,
    featured: true,
    isSale: true,
    specifications: {
      'Display': '55" LED',
      'Resolution': '3840 x 2160 (4K)',
      'Smart Features': 'Yes',
      'HDR': 'Yes',
      'Refresh Rate': '60Hz',
      'HDMI Ports': '3',
      'USB Ports': '2',
    },
    createdAt: '2023-10-20T14:45:00Z',
  },
  {
    id: 'p3',
    title: 'Premium Leather Jacket',
    description: 'Elevate your style with this premium leather jacket. Made from genuine leather with a smooth finish, perfect for casual and semi-formal occasions.',
    price: 249.99,
    categoryId: 'clothing',
    rating: 4.8,
    reviewCount: 137,
    image: 'https://images.pexels.com/photos/16170/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/16170/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/16171/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/16172/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    tags: ['jacket', 'leather', 'fashion', 'outerwear'],
    stock: 28,
    isNew: true,
    specifications: {
      'Material': 'Genuine Leather',
      'Lining': '100% Polyester',
      'Closure': 'Zipper',
      'Pockets': '3 external, 2 internal',
      'Care': 'Professional leather cleaning only',
    },
    createdAt: '2023-12-05T09:15:00Z',
  },
  {
    id: 'p4',
    title: 'Modern Accent Chair',
    description: 'Add a touch of modern elegance to your living space with this beautifully designed accent chair. Features comfortable padding and durable fabric upholstery.',
    price: 159.99,
    originalPrice: 189.99,
    categoryId: 'home',
    rating: 4.6,
    reviewCount: 98,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1350790/pexels-photo-1350790.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/1350791/pexels-photo-1350791.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    tags: ['furniture', 'chair', 'home decor', 'living room'],
    stock: 15,
    isSale: true,
    specifications: {
      'Material': 'Polyester Fabric',
      'Frame': 'Solid Wood',
      'Seat Height': '18 inches',
      'Weight Capacity': '250 lbs',
      'Assembly': 'Required',
    },
    createdAt: '2023-09-30T11:20:00Z',
  },
  {
    id: 'p5',
    title: 'Professional Skincare Set',
    description: 'Transform your skincare routine with this complete professional set. Includes cleanser, toner, serum, and moisturizer formulated for all skin types.',
    price: 79.99,
    originalPrice: 99.99,
    categoryId: 'beauty',
    rating: 4.9,
    reviewCount: 215,
    image: 'https://images.pexels.com/photos/3321416/pexels-photo-3321416.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/3321416/pexels-photo-3321416.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/3321417/pexels-photo-3321417.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/3321418/pexels-photo-3321418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    tags: ['skincare', 'beauty', 'self-care', 'face'],
    stock: 42,
    featured: true,
    isSale: true,
    specifications: {
      'Skin Type': 'All Types',
      'Volume': '50ml each',
      'Benefits': 'Hydration, Brightening, Anti-aging',
      'Free From': 'Parabens, Sulfates, Artificial Fragrances',
      'Cruelty-Free': 'Yes',
    },
    createdAt: '2023-11-25T08:00:00Z',
  },
  {
    id: 'p6',
    title: 'Premium Running Shoes',
    description: 'Designed for serious runners, these premium shoes offer excellent support, cushioning, and durability for optimal performance on any terrain.',
    price: 129.99,
    categoryId: 'sports',
    rating: 4.7,
    reviewCount: 176,
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    images: [
      'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/2529149/pexels-photo-2529149.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      'https://images.pexels.com/photos/2529150/pexels-photo-2529150.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    ],
    tags: ['shoes', 'running', 'athletic', 'sports'],
    stock: 35,
    isNew: true,
    specifications: {
      'Upper': 'Breathable Mesh',
      'Sole': 'Rubber',
      'Cushioning': 'Responsive Foam',
      'Weight': '9.5 oz',
      'Arch Support': 'Medium',
    },
    createdAt: '2023-12-10T15:30:00Z',
  },
  {
    id: 'p7',
    title: 'Bestselling Mystery Novel',
    description: 'Dive into this gripping mystery novel that has topped the charts for weeks. A page-turner that will keep you guessing until the very end.',
    price: 14.99,
    categoryId: 'books',
    rating: 4.8,
    reviewCount: 329,
    image: 'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    tags: ['book', 'novel', 'mystery', 'fiction', 'bestseller'],
    stock: 65,
    featured: true,
    specifications: {
      'Format': 'Hardcover',
      'Pages': '384',
      'Language': 'English',
      'Publisher': 'Penguin Books',
      'Publication Date': 'January 15, 2023',
    },
    createdAt: '2023-08-20T10:00:00Z',
  },
  {
    id: 'p8',
    title: 'Interactive Board Game',
    description: 'Bring family and friends together with this fun, interactive board game. Suitable for ages 8 and up, this game combines strategy and luck for hours of entertainment.',
    price: 34.99,
    originalPrice: 39.99,
    categoryId: 'toys',
    rating: 4.6,
    reviewCount: 146,
    image: 'https://images.pexels.com/photos/3304859/pexels-photo-3304859.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    tags: ['game', 'board game', 'family', 'entertainment'],
    stock: 28,
    isSale: true,
    specifications: {
      'Players': '2-6',
      'Age Range': '8+',
      'Playing Time': '30-60 minutes',
      'Contents': 'Game board, 6 player tokens, 50 cards, dice, instruction manual',
    },
    createdAt: '2023-10-05T13:45:00Z',
  },
  {
    id: 'p9',
    title: 'Digital Fitness Tracker',
    description: 'Monitor your health and fitness goals with this advanced digital tracker. Tracks steps, heart rate, sleep patterns, and more, syncing wirelessly with your smartphone.',
    price: 89.99,
    originalPrice: 109.99,
    categoryId: 'health',
    rating: 4.5,
    reviewCount: 203,
    image: 'https://images.pexels.com/photos/4482900/pexels-photo-4482900.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    tags: ['fitness', 'health', 'tracker', 'wearable tech'],
    stock: 39,
    isSale: true,
    specifications: {
      'Display': 'OLED',
      'Battery Life': 'Up to 7 days',
      'Water Resistance': '5 ATM',
      'Connectivity': 'Bluetooth 5.0',
      'Sensors': 'Heart rate, accelerometer, gyroscope',
    },
    createdAt: '2023-11-18T09:30:00Z',
  },
  {
    id: 'p10',
    title: 'Stainless Steel Water Bottle',
    description: 'Stay hydrated with this premium stainless steel water bottle. Double-walled insulation keeps drinks cold for 24 hours or hot for 12 hours. Eco-friendly and durable.',
    price: 24.99,
    categoryId: 'health',
    rating: 4.7,
    reviewCount: 188,
    image: 'https://images.pexels.com/photos/4045599/pexels-photo-4045599.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    tags: ['water bottle', 'hydration', 'eco-friendly', 'stainless steel'],
    stock: 52,
    isNew: true,
    specifications: {
      'Capacity': '24 oz',
      'Material': '18/8 Stainless Steel',
      'Insulation': 'Double-walled vacuum',
      'Lid Type': 'Screw cap with handle',
      'Dimensions': '10.5" H x 2.9" D',
    },
    createdAt: '2023-12-01T16:15:00Z',
  },
  {
    id: 'p11',
    title: 'Organic Cotton T-Shirt',
    description: 'Experience comfort with this 100% organic cotton t-shirt. Soft, breathable, and eco-friendly, perfect for everyday wear.',
    price: 29.99,
    categoryId: 'clothing',
    rating: 4.6,
    reviewCount: 124,
    image: 'https://images.pexels.com/photos/1484807/pexels-photo-1484807.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    tags: ['t-shirt', 'organic', 'cotton', 'clothing', 'sustainable'],
    stock: 47,
    isNew: true,
    specifications: {
      'Material': '100% Organic Cotton',
      'Fit': 'Regular',
      'Care': 'Machine washable, tumble dry low',
      'Origin': 'Fair Trade Certified',
      'Available Sizes': 'S, M, L, XL, XXL',
    },
    createdAt: '2023-12-08T11:20:00Z',
  },
  {
    id: 'p12',
    title: 'Smart Home Security Camera',
    description: 'Keep your home secure with this advanced smart security camera. Features motion detection, night vision, and real-time alerts to your smartphone.',
    price: 79.99,
    originalPrice: 99.99,
    categoryId: 'electronics',
    rating: 4.4,
    reviewCount: 168,
    image: 'https://images.pexels.com/photos/430208/pexels-photo-430208.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    tags: ['security', 'camera', 'smart home', 'surveillance'],
    stock: 33,
    isSale: true,
    specifications: {
      'Resolution': '1080p HD',
      'Field of View': '130°',
      'Night Vision': 'Up to 30ft',
      'Storage': 'Cloud and local SD card (up to 128GB)',
      'Power': 'Wired, with battery backup',
    },
    createdAt: '2023-10-25T14:00:00Z',
  },
];